tasks:
  - init: sudo apt-get update && sudo apt-get install -y mysql-server
  - init: |
      sudo service mysql start
      sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123456';"
ports:
  - port: 3306
    onOpen: open-preview
